language: go

go:
  - 1.7
  - 1.8

script:
  - go get golang.org/x/tools/cmd/cover
  - go test -v -covermode=atomic -coverprofile=coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)
